### ISSUE TITLE
Build and Deploy a Node.js Project to AWS with GitHub Actions CI/CD.

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Sprint-Week#18]
Attach screenshot of deployment done at the Public IP

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by shradiphylleia** [comment]
can i be assigned this issue.

**Comment by anshikasrivastava17** [comment]
assigned @shradiphylleia

**Comment by anshikasrivastava17** [comment]
> @anshikasrivastava17 Hi i forgot to take the ss of Public IP deployment and I deleted the instance in a hurry bcz of payment issue.I have all the other ss.Will it be okay if I upload those or do i need to do everything again?

@ParthDhavan04 raise the PR will see accordingly

**Comment by Saga690** [comment]
Would like to work on this

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by rampantvoid** [comment]
would like to work on this
