### ISSUE TITLE
Calorie tracker using OOP

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Sprint-Week#21]
Create a calorie tracker using OOP in which you can do following things-
1- An ingredients class that stores the nutrient info (fats, kcal, protein, etc)
2- A dish class which contains a list of all ingredients(with quantity) used and a function to return sum of their respective nutrients
3- A day class vector which stores dishes eaten by user in a day and the quantity of food eaten and shows the total calories eaten in a day, along with the date.
4- Give the user a menu to add more food/ingredient options

**Comment by shradiphylleia** [comment]
can i be assigned this issue?

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by anshikasrivastava17** [comment]
assigned to both

**Comment by anshikasrivastava17** [comment]
@shradiphylleia
- A dish class which contains a list of all ingredients(with quantity) used and a function to return sum of their respective nutrients
- A day class vector which stores dishes eaten by user in a day and the quantity of food eaten and shows the total calories eaten in a day, along with the date.

add these as well and attach screenshots

**Comment by rampantvoid** [comment]
would like to work on this

**Comment by anshikasrivastava17** [comment]
Assigned @rampantvoid
