### ISSUE TITLE
Github's daily counter 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Sprint-Week#22]
Github's daily counter can be used as a writing space. Create a program in any language of your choice that will tell which days the user should contribute in order to get the given text. 

Example: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGI-DaooArBUSm79iD-lT7znAa8QjtKunNow&usqp=CAU

Hint- use a matrix and fill the fields that are occupied, then convert the coordinate position into calendar dates using linear traversal

**Comment by rampantvoid** [comment]
would like to work on this

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by ParthDhavan04** [comment]
Would like to work on this.

**Comment by anshikasrivastava17** [comment]
assigned
