### ISSUE TITLE
Develop a chatbot

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Sprint-Week#3]
Develop a chatbot to efficiently provide users with information and details about the OPEN community, enhancing user engagement and accessibility. You can take the information about OPEN community from the website: [https://upes-open.org/](https://upes-open.org/)
Attach all screenshots depicting the prompts, conversations etc

**Comment by XD-coder** [comment]
@anshikasrivastava17  chatbot from scratch, or can we just existing llm ?

**Comment by ParthDhavan04** [comment]
Can i work on this?

**Comment by anshikasrivastava17** [comment]
any would do but it should be trained on custom data taken from the website, u must attach screenshots of training @XD-coder

**Comment by anshikasrivastava17** [comment]
> Can i work on this?

assigned @ParthDhavan04

**Comment by rampantvoid** [comment]
@anshikasrivastava17 hi can i work on this

**Comment by anshikasrivastava17** [comment]
assigned @rampantvoid

**Comment by rampantvoid** [comment]
@anshikasrivastava17 do we need to build a UI as well or just the chatbot is fine?

**Comment by anshikasrivastava17** [comment]
> @anshikasrivastava17 do we need to build a UI as well or just the chatbot is fine?

yes a basic frontend, not much styling needed

**Comment by Saga690** [comment]
Would like to work on this

**Comment by anshikasrivastava17** [comment]
assigned
