### ISSUE TITLE
 Make an Editing toolkit 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Sprint-Week#8]
Develop a comprehensive image editing toolkit using vanilla JS, ensuring a diverse set of functionalities.

**Comment by rampantvoid** [comment]
@anshikasrivastava17 hi i would like to work on this

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by ParthDhavan04** [comment]
Can i work on this?

**Comment by Saga690** [comment]
Would like to work on this

**Comment by anshikasrivastava17** [comment]
assigned
